
name: whoami-ci

on:
  workflow_dispatch:
  push:
    paths:
      - "app/**"
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:

  main:
    name: build and push
    runs-on: ubuntu-latest
    env:
      GO_VERSION: stable
      GOLANGCI_LINT_version: v1.58.0
      CGO_ENABLED: 0
      IMAGE_NAME: whoami

    steps:

      # Checkout code
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # Set up Go env
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      
      # Install golangci-lint
      - name: Check and get dependencies
        working-directory: ./app
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_LINT_VERSION}
          golangci-lint --version

      # Run linters, tests and build
      - name: Run linters, tests and build
        working-directory: ./app
        run: make check test

      # Run build
      - name: Run build
        working-directory: ./app
        run: make build

      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD-HH

      - name: Get commit short sha
        id: sha
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      
      # Create the image
      - name: Make Image
        working-directory: ./app
        run: |
          make image IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.current-time.outputs.formattedTime }}-${{ steps.sha.outputs.sha_short }}"
          make image IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      # Have access to provide Docker hub
      - name: dockerhub-login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push "${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.current-time.outputs.formattedTime }}-${{ steps.sha.outputs.sha_short }}"
          docker push "${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest